FROM python:3.11-slim
RUN pip install --no-cache-dir mlflow psycopg2-binary boto3 gunicorn
EXPOSE 5000
CMD mlflow server \
  --backend-store-uri ${MLFLOW_BACKEND_STORE_URI} \
  --artifacts-destination ${MLFLOW_ARTIFACT_ROOT} \
  --serve-artifacts \
  --host 0.0.0.0 --port 5000 \
  --allowed-hosts "*" \
  --cors-allowed-origins "*"
